# Generated by Django 5.1.2 on 2024-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_commande', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
