# Generated by Django 5.1.2 on 2024-11-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
