# Generated by Django 5.1.2 on 2024-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_commander_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='date_commande',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
