# Generated by Django 5.1.2 on 2024-11-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_commander_date_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='total',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
